name: build.yml

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-test-sonar-docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      # 3. Instalar dependencias y correr tests
      - name: Build & Unit Tests (Maven)
        run: mvn -B clean verify

      # 4. SonarCloud Analysis (opcional si está configurado)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5. Publicar el archivo JAR como artefacto
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: petstore-backend
          path: target/lab2-ArquiSoft-petstore.jar

      # 6. Login a Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Build imagen Docker
      - name: Build Docker image
        run: docker build -t juansn/lab2-arquisoft2025:latest .

      # 8. Push imagen a DockerHub
      - name: Push Docker image
        run: docker push juansn/lab2-arquisoft2025:latest
