name: CI - Maven build & tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    name: Unit Tests (Java 21)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: petstore-feature5-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Set up JDK 21 and cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Show Java version
        run: java -version

      - name: Build and run tests (includes checkstyle)
        run: ./mvnw -B -V -U verify
