name: CI/CDp - Maven build & tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    name: Unit Tests (Java 21)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: petstore-feature5-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Set up JDK 21 and cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Show Java version
        run: java -version

      - name: Build and run tests (includes checkstyle)
        run: ./mvnw -B -V -U verify

  sonar:
    # Depends on tests job
    needs: tests
    name: SonarCloud analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: petstore-feature5-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Show Java version
        run: java -version

      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -z "${SONAR_TOKEN}" ]; then
            echo "Warning: SONAR_TOKEN secret is not set. Skipping SonarCloud analysis.";
            exit 0;
          fi
          # Run Maven verify + Sonar. Update sonar.projectKey and sonar.organization to match your SonarCloud setup.
          ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=JuanSebastian05_Lab2-ArquiSoft2025 -Dsonar.organization=juansebastian05-1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}
 
